### ISSUE TITLE
Unable to authenticate using AAD 

### ISSUE THREAD

**Issue by rock-it-rob** [microsoftgraph/msgraph-training-java#1]
I receive the following after entering the access code at microsoft.com/devicelogin:

AADSTS500201: We are unable to issue tokens from this API version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.

**Comment by jasonjoh** [comment]
Based on the error, it sounds like you're using a personal account. Unfortunately that's a limitation of Azure's OAuth device code flow implementation. They only support work/school accounts, not personal accounts.

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code

**Comment by rock-it-rob** [comment]
Yes, I made a new personal account to test this.

**Comment by jasonjoh** [comment]
Fair point, it could be clearer. Those instructions aren't wrong: you can use a personal account to register the application,  you just can't use a personal account to sign in to the app using the auth flow the sample uses.
