### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by hamedisu** [microsoftgraph/msgraph-training-java#13]
hi
many thanks for your tutorial
but despite I follow the tutorial but at the end I encounter to this error:

> Task :compileJava
C:\firefox_Driver\msgraph-training-java-master\demo\graphtutorial\src\main\java\graphtutorial\Authentication.java:38: error: ca
nnot find symbol
        Set<String> scopeSet = Set.of(scopes);
                                  ^
  symbol:   method of(String[])
  location: interface Set
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan
to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
1 actionable task: 1 executed

I would be pleased if you can help me!

I'm new to java and ms graph and I just need to upload an excel file to one drive programmatically using java.

many thanks in advance!

**Comment by jasonjoh** [comment]
[Set.of](https://docs.oracle.com/javase/9/docs/api/java/util/Set.html#of--) was added in Java 9, so you may be using an older version. The tutorial was written with [Java 14](https://cr.openjdk.java.net/~iris/se/14/build/latest/api/).

**Comment by hamedisu** [comment]
> [Set.of](https://docs.oracle.com/javase/9/docs/api/java/util/Set.html#of--) was added in Java 9, so you may be using an older version. The tutorial was written with [Java 14](https://cr.openjdk.java.net/~iris/se/14/build/latest/t

**Comment by hamedisu** [comment]
> [Set.of](https://docs.oracle.com/javase/9/docs/api/java/util/Set.html#of--) was added in Java 9, so you may be using an older version. The tutorial was written with [Java 14](https://cr.openjdk.java.net/~iris/se/14/build/latest/api/).

thank you so much
I update the jdk to 14 and your sample code work well.
but what should I do for uploading a file on my one drive?

in fact, I want to upload (update) a file (excel file) on my onedrive programmatically every 10 minutes. 
for more details, this file is embedded on my website and I want the data of this excel file be updated automatically.
I have written java program that update the file automatically (by getting new data from a site). but how can I upload the new file on my onedrive? 
would you please help me?
many tanks in advance for your help.

**Comment by jasonjoh** [comment]
https://docs.microsoft.com/graph/sdks/large-file-upload?view=graph-rest-1.0&tabs=java does exactly that.

**Comment by hamedisu** [comment]
dear jasonjoh 
thank you very much for your guide and help... 
after a day working on it, I can now upload the file using java...
I don't know how to thank you for your kind help...

now I have another question. 
with your sample code each time I run the application, I should sign in microsoft... Is it possible to store my user and password in the app to avoid manual sign in?
thanks a lot.

**Comment by jasonjoh** [comment]
Storing username/password is a bad practice. You should look at [token cache customization](https://docs.microsoft.com/azure/active-directory/develop/msal-java-token-cache-serialization) to implement secure storage for your tokens.
