### ISSUE TITLE
UpdateAppForAppOnlyAuth.ps1 has an invalid source code

### ISSUE THREAD

**Issue by FumioKishida** [microsoftgraph/msgraph-training-java#49]
I executed UpdateAppForAppOnlyAuth.ps1 but the following error has appeared.
I think the shell script needs to be fixed.

Get-MgApplication : The specified filter to the reference property query is currently not supported.
発生場所 Z:\msgraph-training-java\demo\UpdateAppForAppOnlyAuth.ps1:31 文字:1
+ $appRegistration = Get-MgApplication -Filter ("appId eq '" + $AppId + ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ConsistencyLe...ndProperty =  }:<>f__AnonymousType24`9) [Get-MgAppl
   ication_List1]、RestException`1
    + FullyQualifiedErrorId : Request_UnsupportedQuery,Microsoft.Graph.PowerShell.Cmdlets.GetMgApplication_List1

**Comment by jasonjoh** [comment]
This file has been replaced with a stand-along file in /app-auth/RegisterAppForAppOnlyAuth.ps1.
