### ISSUE TITLE
Don't Use Static Methods

### ISSUE THREAD

**Issue by opticyclic** [microsoftgraph/msgraph-training-java#58]
### Where did you get the code?

- [ x] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

Every method is static.
This is bad practice and not good as an example as you don't want to encourage this behaviour.
Create an instance of the class and make it so they aren't static.

**Comment by jasonjoh** [comment]
Why do you say "this is a bad practice"? I understand static classes/methods come with limitations, but this was meant to be a very simple example to get you to the point of calling Graph APIs with the SDK quickly.
