### ISSUE TITLE
PublicClientApplication class not available

### ISSUE THREAD

**Issue by NguyenDa18** [microsoftgraph/msgraph-training-java#6]
Hi I was working through the tutorial and came across the [this error](url) at step "Add Azure AD Authentication". Then when I tried running the demo after cloning this project I got the same error when running the 03-add-msgraph project. I checked the [PublicClientApplication class](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/PublicClientApplication.java) and it is available to use, so now I'm stumped on why the class is not being found. For both projects I made sure to change the oAuth.properties files to use my Azure app config. Thanks
<img width="979" alt="Screen Shot 2020-02-10 at 11 42 48 AM" src="https://user-images.githubusercontent.com/14105469/74183849-9f047c80-4bfa-11ea-9285-f3ca96fd681e.png">

**Comment by jasonjoh** [comment]
Do you have this problem if you use the msal4j version from the instructions (1.1.0)? There may be some version difference. Other than that, it may be an issue with your class path.

**Comment by NguyenDa18** [comment]
Hi @jasonjoh I get the same issue when decreasing the version to 1.1.0 but I will check if it is an issue with my classpath. My coworker was able to get the example running on his Windows machine so I will check how Homebrew configured my maven and java. Thanks for replying.
